targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: 'lib/core/api/'
          input_url: 'api.json'
          output_folder: 'lib/core/api/generated/'
          separate_models: true
          use_path_for_request_names: true
          split_by_tag: true
          generate_first_succeed_response: true
          override_equals_and_hashcode: true
