import 'master_listing.dart';

/// Detailed profile data shown on the Provider Profile screen.
///
/// Wraps the [MasterListing] summary (already shown on the discovery
/// card) and adds the data needed for the equity chart, stats table,
/// symbol distribution, and recent activity table.
///
/// In Phase E the equity history + recent activity will be derived from
/// `getOrderHistory` calls scoped to the provider's master account; the
/// stats become a server-side aggregation. For now (D.5) all of this is
/// generated by the mock repository.
class ProviderProfile {
  final MasterListing summary;

  /// Equity vs balance over time. Charted as two lines (equity green,
  /// balance blue). Optional [EquityPoint.depositChange] surfaces as
  /// markers on the timeline.
  final List<EquityPoint> equityHistory;

  final ProviderStats stats;

  /// Symbol → fraction of total volume traded. Sums to ~1.0. Charted as
  /// a pie/donut.
  final Map<String, double> symbolDistribution;

  final List<TradingActivity> recentActivity;

  const ProviderProfile({
    required this.summary,
    required this.equityHistory,
    required this.stats,
    required this.symbolDistribution,
    required this.recentActivity,
  });
}

class EquityPoint {
  final DateTime date;
  final double equity;
  final double balance;

  /// Non-null when this point coincides with a deposit/withdrawal.
  /// Positive = deposit, negative = withdrawal. Renders as a marker on
  /// the chart.
  final double? depositChange;

  const EquityPoint({
    required this.date,
    required this.equity,
    required this.balance,
    this.depositChange,
  });
}

class ProviderStats {
  final int totalTrades;

  /// 0.0–1.0.
  final double winRate;

  /// Gross profit / gross loss. > 1 is profitable.
  final double profitFactor;

  final double avgWin;
  final double avgLoss;
  final Duration avgHoldTime;
  final int maxWinStreak;
  final int maxLossStreak;

  const ProviderStats({
    required this.totalTrades,
    required this.winRate,
    required this.profitFactor,
    required this.avgWin,
    required this.avgLoss,
    required this.avgHoldTime,
    required this.maxWinStreak,
    required this.maxLossStreak,
  });
}

class TradingActivity {
  final String symbol;
  final TradeDirection direction;
  final double lots;
  final DateTime openTime;

  /// Null = position is still open.
  final DateTime? closeTime;

  /// Null = position is still open OR P&L not yet realised.
  final double? pnl;

  const TradingActivity({
    required this.symbol,
    required this.direction,
    required this.lots,
    required this.openTime,
    this.closeTime,
    this.pnl,
  });

  bool get isOpen => closeTime == null;
}

enum TradeDirection { buy, sell }
